config/routes.rb
Rails.application.routes.draw do

  root to: 'farms#index'
  
  resources :farms, only: [:index, :show] do
    collection do
      get :search, to: "farms#search"
    end
    resources :reviews, only: [:create, :edit, :update]
  end
  
  namespace :farmer do
    resources :farms, only: [:new, :create, :edit, :update]
    get '/users/dashboard/:id', to: '/farmer/users#dashboard'
  end
  
  resources :users, only: [:create, :show]
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  get '/farms/search', to: 'farms#search'
  
  resources :regions, only: [:show]
  
end

app/models/farm.rb
class Farm < ActiveRecord::Base
  
  include Sluggable
  
  has_many :reviews
  belongs_to :region
  belongs_to :farmer, foreign_key: "user_id", class_name: "User"
  
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true, uniqueness: true
  validates :description, presence: true
  validates :region_id, presence: true
  
  sluggable_column :name
     
  def self.latest_farms
    Farm.order('created_at DESC').first(3)
  end
  
  def self.search_farms(term)
    return [] if term.blank?
    where("name ILIKE ? or address ILIKE ? or description ILIKE ?", "%#{term}%", "%#{term}%", "%#{term}%")
  end

end 

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :farms
  
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :farm
end

app/models/user.rb
class User < ActiveRecord::Base
  
  include Sluggable
  
  has_many :reviews
  has_secure_password validations: false
  has_many :farms

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 7}
  validates :name, presence: true, uniqueness: true
  
  sluggable_column :name
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end
  
   def require_user
    redirect_to login_path unless current_user
   end
  
  def logged_in?
    !!current_user
  end
  
end

app/controllers/concerns/sluggable.rb
module Sluggable
  extend ActiveSupport::Concern

  included do
    before_save :generate_slug!
    class_attribute :slug_column
  end

  def to_param
    self.slug
  end

  def generate_slug!
    the_slug = to_slug(self.send(self.class.slug_column.to_sym))
    obj = self.class.find_by slug: the_slug
    count = 2
    while obj && obj != self
      the_slug = append_suffix(the_slug, count)
      obj = self.class.find_by slug: the_slug
      count += 1
    end
    self.slug = the_slug.downcase
  end

  def append_suffix(str, count)
    if str.split('-').last.to_i != 0
      return str.split('-').slice(0...-1).join('-') + "-" + count.to_s
    else
      return str + "-" + count.to_s
    end
  end

  def to_slug(name)
    str = name.strip
    str.gsub! /\s*[^A-Za-z0-9]\s*/, '-'
    str.gsub! /-+/,"-"
    str.downcase
  end

  module ClassMethods
    def sluggable_column(col_name)
      self.slug_column = col_name
    end
  end
end

app/controllers/farmer/farms_controller.rb
class Farmer::FarmsController < FarmersController
  before_filter :require_user
  before_filter :require_farmer
    
  def new
    @farm = Farm. new
  end    
  
  def create
    @farm = Farm.create(farm_params)
    
    if @farm.save
      flash[:success] = "Your farm profile was created."
      redirect_to farm_path(@farm)
    else
      render :new
    end
  end
  
  def edit
    @farm = Farm.find(params[:id])
    require_same_farmer
  end
  
  def update
    @farm = Farm.find(params[:id])
    if logged_in? and (current_user == @farm.farmer) or current_user.admin?
      if @farm.update(farm_params)
        flash[:success] = "Your farm profile was updated."
        redirect_to farm_path(@farm)
      else
        render :edit
      end
    else
      redirect_to farm_path(@farm) 
    end
  end

  
  private
  
  def farm_params
    params.require(:farm).permit(:name, :address, :description, :email, :phone, :website, :price, :region_id, :photo)
  end
end

app/controllers/farmer/users_controller.rb
class Farmer::UsersController < FarmersController
  before_filter :require_user
  before_filter :require_farmer
  
  def dashboard
    @farmer = User.find_by slug: (params[:id])
    if @farmer
      dashboard_owner
      @farms = @farmer.farms.all
    else 
      redirect_to root_path
    end
  end  
  
  private
  
  def dashboard_owner
    unless logged_in? and (current_user == @farmer) or current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
  before_filter :require_user
  before_filter :require_farmer 
  
  def require_farmer
    unless current_user.farmer? or current_user.admin?
      redirect_to root_path
    end
  end   
  
  def require_same_farmer
    unless logged_in? and (current_user == @farm.farmer) or current_user.admin?
      redirect_to farm_path(@farm) 
    end
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  def index
    @farms = Farm.all
  end
  
  def show
    @farm = Farm.find_by slug: params[:id]
    if @farm == nil
      redirect_to root_path 
    else
      @reviews = @farm.reviews
      @review = Review.new
    end
  end
  
  def search
    @results = Farm.search_farms(params[:term])
  end
 
   private
  
   def post_params
     params.require(:farm).permit(:name, :address, :description, :email, :phone, :website)
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  
  def show
    @region = Region.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user
 # before_action :require_same_user, only: [:update]

  def create
    @farm = Farm.find_by slug: params[:farm_id]
    @review = @farm.reviews.build(params.require(:review).permit(:content))
    @review.creator = current_user
    if @review.save
      flash[:success] = "Thank you for your review."
      redirect_to farm_path(@farm)
    else
      @reviews = @farm.reviews.reload
      render 'farms/show'
    end
  end
  
  def edit
    @review = Review.find(params[:id])
    @farm = @review.farm
    require_same_user
  end
  
  def update   
    @review = Review.find(params[:id])
    @farm = @review.farm
    require_same_user
  
    if @review.update(review_params)
      flash[:success] = "The review was updated"
      redirect_to farm_path(@farm)
    else
      render :edit
    end
  end
 
  private
  
  def require_same_user
    redirect_to farm_path(@farm) unless logged_in? and (current_user == @review.creator)
  end
    
  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    redirect_to root_path if current_user
  end
  
  def create
    user = User.where(email: params[:email]).first
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:danger] = "There's something wrong with your username or password."
      redirect_to login_path
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end
  
  def show
    @user = User.find_by slug: params[:id] 
    redirect_to root_path if @user == nil
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/farmer/farms/edit.html.haml
.farm-profile
  %h3 Edit your farm profile

  =render 'farms/farm', farm: @farm

app/views/farmer/farms/new.html.haml
.farm-profile
  %h3 Create your farm profile

  =render 'farms/farm', farm: @farm

app/views/farmer/users/dashboard.html.haml
.container.dashboard
  %h2 #{@farmer.name}'s Dashboard

  .row
    %h4= link_to "Create new farm profile", new_farmer_farm_path

  .row
    %h2 Current farm profiles
    - @farms.each do |farm|
      .col-sm-4
        %h4= link_to farm.name, farm_path(farm)

app/views/farms/_farm.html.haml
= bootstrap_form_for [:farmer, @farm] do |f|

    = f.text_field :name
    = f.text_field :address
    = f.text_area :description, rows: 8, class: "col-md-6"
    = f.text_field :email
    = f.text_field :phone
    = f.text_field :website
    = f.text_field :price
    = f.text_field :photo
    = f.select :region_id, options_for_select(Region.all.map {|region| [region.name, region.id]})

    %input(type="submit" value="Add Farm" class="btn btn-success")  

app/views/farms/index.html.haml
%article.farm
  .container-fluid
    .jumbotron
      %h1 Farmstays
      %h3 Search for farmstays around the world
      
    .latest-farms
      %h3 Latest Farms
      .row      
        - @farms.latest_farms.each do |farm|
          .col-sm-4    
            = link_to image_tag(farm.photo, width: '350')
            %h4= link_to farm.name, farm_path(farm)
      %h3 See what our farms have to offer
    
  .container
    .row
      .fadein
        = image_tag("coffee.jpg")
        = image_tag("date.jpg")
        = image_tag("horse.jpg")          
        = image_tag("llama.jpg")
        = image_tag("pepper.jpg")
        = image_tag("pony.jpg")
        = image_tag("reindeer.jpg")
        = image_tag("sheep.jpg")
        = image_tag("wine.jpg")

.container
  .row
    .about
      %h3#about About Farmstays
      %h4#about-description We are a listing of farmstays around the world.  We can help you find out about the most interesting destinations.  Many of the farms listed here offer some of the best travel bargains you will find. Accomodations range from luxurious to adventurous. Whether you want to ride an elephant or learn about permaculture, there is something for you here.  
  
  
:javascript 
  src="js/home.js" type="text/javascript" charset="utf-8"
    
%footer
  = render 'layouts/footer'
  

    

app/views/farms/search.html.haml
.container.results
  %h4 Your search results
  - @results.each do |farm|
    %h3= link_to farm.name, farm_path(farm)
    %h4= farm.address
    %p= farm.description

app/views/farms/show.html.haml
.container.farm-info
  .farm-show-message
    = render 'shared/messages' 
  = link_to image_tag(@farm.photo, width: '700')
  %h2= @farm.name
  %h4.heading Location
  %p= @farm.address
  %h4.heading Contact
  %p Email: #{@farm.email}
  %p Phone: #{@farm.phone}
  %p Website: #{@farm.website}
  %h4.heading Price: $#{@farm.price}
  %h4.heading Description
  %p= @farm.description

  %h4.heading Reviews for this Farm (#{@reviews.count})
  - @reviews.each do |review| 
    .well.farm-reviews
      %h4= link_to review.creator.name, user_path(review.creator)
      %p= review.updated_at
      %p= review.content
      - if logged_in? && current_user == review.creator
        = link_to 'Edit this review', edit_farm_review_path(@farm, review)
  - if logged_in?
    %h4.heading Write a review
    - review = @review
    = render 'reviews/review', review: review 

app/views/layouts/_footer.html.erb
<div class = "container">
  <div class="footer">
    <h4>Coded by Ashlynn Pai</h4>
  <p>Sunset photo by Tony Fischer, CC by 2.0.  Attributions for other photos are in the farm descriptions.</p>
  </footer>
</div>

app/views/layouts/_navigation.html.erb
  <ul class="nav navbar-nav">
    <li class='btn-group nav_item'>
      <%= link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do %>
        <h4>Choose a Region <span class='caret'></span></h4>
      <% end %>
        <ul class='dropdown-menu'>
          <% Region.all.each do |region| %>
            <li>
              <%= link_to region.name, region_path(region)%>
            </li>
          <% end %>
        </ul>
    </li>
       
    <li>   
        <div class="form-group navbar-form" role="search">
          <%= form_tag farms_search_path, :method => 'get' do %>
          <%= text_field_tag :term, nil, :class => 'search-box', :placeholder => 'Search Farms by keyword' %>
          <%= submit_tag "Search Farms", :class => 'btn' %>
          <% end %>
        </div>
    </li>
  </ul>
   
  <ul>
    <li>
      <% if logged_in? %>
         <li class='btn-group nav_item navbar-right' id='user-item'>
           <%= link_to('', class: 'dropdown-toggle', 'data-toggle' => 'dropdown') do %>
             <%= current_user.name %>
            <span class='caret'></span>
          <% end %>
          <ul class='dropdown-menu dropdown-menu-left'>
            <li><%= link_to user_path(current_user) do %>
              <i class='icon-circle-arrow-left'></i>
              My public profile
            <% end %>
            </li>           
            <% if current_user.farmer? %>
            
            <li><%= link_to farmer_path(current_user) do %>
                 <i class='icon-circle-arrow-left'></i>
                 Dashboard
               <% end %>
               </li>
            <% end %>
          <li><%= link_to logout_path do %>
            <i class='icon-circle-arrow-left'></i>
            Logout
          <% end %>
        </li>
    </ul>
    <% else %>
      <li>
        <div class='nav_item navbar-right' id='user-item'>
          <%= link_to 'Log in', login_path, class: '' %>
         </div>
     </li>
     <li>
       <div class='nav_item navbar-right' id='user-item'>
        <%= link_to 'Register', register_path %>
       </div>
     </li>
   <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Farmstays</title>
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans|Montserrat' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="main">
  <div class="container-fluid">
    <header>
      <nav class="navbar navbar-fixed-top" role="navigation">
        <%= render 'layouts/navigation' %>
      </nav>
    </header>
  </div>
  
  <div class="container-fluid">
    <div class="main-content">
    <%= yield %>
    </div>
  </div>

</body>

</html>

app/views/regions/show.html.haml
.container
  .region-list
    %h2= @region.name
    %h4 #{@region.farms.count} farms listed for this region
    - @region.farms.each do |farm|    
      .row
        .col-sm-6 
          %h3= link_to farm.name, farm_path(farm)
          = link_to image_tag(farm.photo, width: '350')
        .col-sm-6
          .compact-farm
            %h4.heading Location
            %p= farm.address
            %h4.heading Contact
            %p Email: #{farm.email}
            %p Phone: #{farm.phone}
            %p Website: #{farm.website}
            %h4.heading Price: $#{farm.price}

app/views/reviews/_review.html.haml
= form_for [@farm, review] do |f|
  %fieldset
  .form-group
    %br
    =f.text_area :content, rows: 6, class: "form-control" 
    %fieldset.form-group.actions.clearfix
    %input(type="submit" value="Submit" class="btn btn-success")

app/views/reviews/edit.html.haml
.container.farm-info
  .row
    %h4.heading Edit your review
    .col-sm-8
      - review = @review
      = render 'reviews/review', review: review 

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/users/new.html.haml
%section.register.container
  .row
    %h5 This site is currently in demo status. The farms here are fictional and the database may be reset at any time.
    .col-sm-8
      .form-horizontal
        = bootstrap_form_for @user do |f|
          %header
            %h3 Sign up to use all our features.
          %fieldset
            .col-sm-6
              = f.text_field :email, label: "Email"
              = f.password_field :password, label: "Password"
              = f.password_field :password_confirmation, label: "Confirm Password"  
              = f.text_field :name , label: "Name"
          %fieldset.actions.control-group
            .controls
              = f.submit(@user.new_record? ? 'Register' : 'Update Profile', class: 'btn btn-success') 

app/views/users/show.html.haml
.container.user-profile-public
  %h3= @user.name
  %h3 Reviews
  - @user.reviews.each do |review|
    .well
      %h4= link_to review.farm.name, farm_path(review.farm)
      %p= review.updated_at
      %p=  review.content
  